events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen 80;
        server_name localhost;

        location /stub_status {
            stub_status on;
            access_log off;
        }

        access_log /var/log/nginx/custom_access.log combined;
        error_log /var/log/nginx/custom_error.log warn;
        
        location / {
            proxy_pass http://api:8070;
            proxy_http_version 1.1;
        }
    }
}
