

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/targets.json:/etc/prometheus/targets.json
      - ./prometheus/alertrules.yml:/etc/prometheus/alertrules.yml
    command:
      - '--storage.tsdb.path=/prometheus'
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=1d'
    restart: always
    networks:
      - monitor

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    restart: always
    networks:
      - monitor

  
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - 9100:9100
    restart: always
    networks:
      - monitor

  # server:
  #   image: bureck/ws101:latest
  #   container_name: webapp
  #   ports:
  #     - 8080:8080
  #   environment:
  #     - JWT_SECRET=22719f3cc69f3484569a2414d1d847c9799c8000aa99bb039905a391942ab977744ee41efa55292d64c
  #     - DB_URL=postgresql://postgres:postgres@db:5432/monitor
  #     - JWT_ALGORITHM=HS256
  #   restart: always
  #   networks:
  #     - monitor

  # db:
  #   image: postgres:latest
  #   container_name: db
  #   ports:
  #     - 5432:5432
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=monitor
  #   restart: always
  #   networks:
  #     - monitor



networks:
  monitor:
    driver: bridge