apiVersion: v1
kind: Pod
metadata:
  name: single-pod
  labels:
    app: single-pod

spec:
  containers:
    - name: k8s-single-pod
      image: bureck/k8s-single-pod:latest
      ports:
      - containerPort: 8000
